server:
  port: 8080
spring:
  application:
    name: workreport
  datasource:
    url: jdbc:postgresql://localhost:5432/workreport
    username: postgres
    password: 1234qwer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: namkunwooo@gmail.com
    password: hpdi mdev yris pcym
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: pdiw8fwef9wFefqvli28vwef7qwd8hfwq923fjwefwe09fwv